trelivery/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

""" Por su caracter de "comodin" obligatoriamente tiene que ser la última """
urlpatterns += [
    url(r'', include('visitantes.urls', namespace='visitantes')),
]

visitantes/urls.py
from django.conf.urls import url
from visitantes import views

urlpatterns = [
    url(r'^$', views.unica, {'plantilla': 'visitantes_entrada'},
        name='inicio'),
    url(r'^termos/$', views.unica, {'plantilla': 'visitantes_entrada'},
        name='termos'),
    url(r'^privacidade/$', views.unica, {'plantilla': 'visitantes_entrada'},
        name='privacidade'),
    url(r'^como-pedir/$', views.unica, {'plantilla': 'visitantes_entrada'},
        name='como-pedir'),
    url(r'^sobre-nos/$', views.unica, {'plantilla': 'visitantes_entrada'},
        name='sobre-nos'),
    url(r'^cadastre-se/$', views.unica, {'plantilla': 'visitantes_entrada'},
        name='cadastre-se'),
    url(r'^cliente-login/$', views.unica, {'plantilla': 'visitantes_entrada'},
        name='cliente-login'),
    url(r'^cadastre-seu-restaurante/$', views.unica,
        {'plantilla': 'visitantes_entrada'}, name='cadastre-seu-restaurante'),
]

""" urls de búsqueda de restaurantes """
urlpatterns += [
    url(r'^lista-restaurantes/(?P<cep>\d{2}\.\d{3}\-\d{3})/$',
        views.restaurantesPorCEP,
        {'plantilla': 'visitantes_listarestaurantes'},
        name='restaurantesporcep'),
    url(r'^lista-restaurantes/(?P<municipio>.+\-[A-Z]{2})/$',
        views.restaurantesPorMunicipio,
        {'plantilla': 'visitantes_listarestaurantes'},
        name='restaurantesporcep'),
]

""" urls de acceso a cartas de restaurante """
urlpatterns += [
    url(r'^cardapio/(?P<restaurante>[A-Za-z-]+)/$',
        views.muestraCarta,
        {'plantilla': 'visitantes_carta'},
        name='carta'),
]

visitantes/models.py
from django.db import models

# Create your models here.

visitantes/views.py
from django.shortcuts import render

# Create your views here.


def unica(request, plantilla):
    return render(request, plantilla)


def buscaRestaurantes(request, plantilla):
    return render(request, plantilla)


def restaurantesPorCEP(request, cep, plantilla):
    return render(request, plantilla)


def restaurantesPorMunicipio(request, municipio, plantilla):
    return render(request, plantilla)


def muestraCarta(request, restaurante, plantilla):
    return render(request, plantilla)

visitantes/templates/includes/nav1.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'visitantes:inicio' %}">IFlunch</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="{% if request.resolver_match.url_name == 'sobre-nos' %}active{% endif %}">
              <a href="{% url 'visitantes:sobre-nos' %}">Sobre nós</a></li>
        <li class="{% if request.resolver_match.url_name == 'cadastre-seu-restaurante' %}active{% endif %}">
              <a href="{% url 'visitantes:cadastre-seu-restaurante' %}">Cadastre seu Restaurante</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="{% if request.resolver_match.url_name == 'cadastre-se' %}active{% endif %}">
              <a href="{% url 'visitantes:cadastre-se' %}">
                <span class="glyphicon glyphicon-user"></span> Cadastre-se</a></li>
        <li class="{% if request.resolver_match.url_name == 'cliente-login' %}active{% endif %}">
                <a href="{% url 'visitantes:cliente-login' %}">
                    <span class="glyphicon glyphicon-log-in"></span> Clientes</a></li>
      </ul>
    </div>
  </div>
</nav>